### ISSUE TITLE
基于Travis CI实践

### ISSUE THREAD

**Issue by Genluo** [Genluo/Precipitation-and-Summary#102]
![CI/CD 流程](https://www.redhat.com/cms/managed-files/ci-cd-flow-desktop_1.png)

# 构建流程

针对工具库的构建，需要使用[云构建](https://toutiao.io/posts/251943/app_preview)，保证结果的一致，这里选择使用`Travis CI`作为`CI`工具（文档真的非常完善），项目的接入过程中主要分为这样几步骤：

* 登录[travis](https://www.travis-ci.org/)进行用户或者群组的授权，并在[`travs`](https://www.travis-ci.org/account/repositories)开启对应的`Legacy Services Integration`

* 项目中推送`.travis.yml`，并在其中配置对应的规则，具体配置可以查看官方引导： [click me](https://docs.travis-ci.com/user/tutorial/)
* 配置完成之后，仓库每次`push commit`将在`travis virtual machine`中执行对应的依赖安装、项目构建等过程

```yaml
language: node_js
cache:
  directories:
  - node_modules
node_js:
- lts/*
install:
- npm install
- npm run build
```

# 测试流程

当构建完成之后，如果每次构建完成，在`travis virtual machine`上运行对应项目的测试用例，防止单次`commit`不带来新的问题，这里我继续使用`travis`的相关能力

## 1. 执行测试

* `.travis.yml`中配置对应的`script`命令，运行本地的`npm run test`命令执行对应的测试用例
* 如果执行报错将导致这次CI流程报错
* 如果测试完成，同时可以生成对应的覆盖度文档，如果使用的是`jest`，可以在`cli`中添加`--coverage`即可
* 测试完成之后，需要更加可视化的分析，可以使用`codecov`将生成结果进行上传分支

## 2. coverage分析

- 测试完成之后，可以通过`codecov`进行代码的覆盖度分析，并生成对应的`badge`更好的展示我们的项目
- 首先登录[codeco](https://about.codecov.io/)v进行授权，找到对应的仓库，获取对应的`Repository Upload Token`
- 将获取的``Repository Upload Token``作为`travis`的环境变量进行保存
- `.travis.yml`中配置对应`codecov`命令推送测试结果

```yaml
language: node_js
cache:
  directories:
  - node_modules
node_js:
- lts/*
install:
- npm install
- npm install codecov -g
script:
- npm run test
after_success:
- codecov -f coverage/*.json
```

# 发布流程

### npm version

```shell
npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease [--preid=<prerelease-id>] | from-git]
```

其中各个参数代表的意义如下：

```shell
major # 主版本号
minor # 次版本号
patch # 补丁号
premajor # 预备主版本
prepatch # 预备次版本
prerelease # 预发布版本
```

命令执行过程中，`npm`完成了这样几件事情：

1. 更改package.json中的version
2. 如果当前是`git`仓库，同时将创建一个对应的`git tag`标签，可以通过`--no-git-tag-version`参数禁止生成`tag`信息
3. 保存修改并生产一个新的commit，其commit内容为`Upgrade to v0.0.1`可以通过`-m`参数自定义commit信息

```shell
npm version major -m "Upgrade to %s"  # %s 会自动替换成版本号
```

### git tag

> Like most VCSs, Git has the ability to tag specific points in a repository’s history as being important. Typically, people use this functionality to mark release points (`v1.0`, `v2.0` and so on). 

详细的使用方法请执行`git tag --help`，会有详细的`man`文档输出

### 1）现有的发布流程（单分支）

1. 根据`changelog`生成新的版本号
2. 修改`package`中的`version`字段
3. 执行`git commmit`、`git tag`、`git push`
4. `Ci` 监听`tag`，进行`npm`包的发布

### 2）理想发布流程（单分支）

1. 执行`npm version`会自动执行`commmit`、`tag`、`push`等流程，
2. `package script`中添加如下命令，每次执行`npm version `命令，自动将当前`commit`、`tag`推送到远程仓库，从而触发`travis`进行发布

```
"postversion": "git push --follow-tags"
```

3. 每次调用`npm version`，调用`conventional-changelog`生成对应版本的`changlog`

```
"version": "conventional-changelog -p angular -i CHANGELOG.md -s && git add CHANGELOG.md"
```

4. 自动生成`changlog`，但是并不会生成的对应的`Github Release`，需要使用到[github-release-from-changelog](https://github.com/MoOx/github-release-from-changelog)根据`changelog`生成对应的信息，因为调用过程中需要`GITHUB_TOKEN`，所以我将这一步放在`Travis`中执行

```yaml
after_deploy:
- npm install github-release-from-changelog
- github-release-from-changelog --filename CHANGELOG.md
```

* 这里需要注意`package repository.url`需要是`https`格式的

## 资源发布（NPM & gh-pages）

* `travis`文档非常完整，其中函数`npm`和`Github Pages`和`Github releases`发布，文档请: [click me](https://docs.travis-ci.com/user/deployment/)
* 其中针对这些类型的发布，需要npm发布秘钥和github push的token
* 获取到之后，可以将这两个值保存为`env`对应的配置为`NPM_TOKEN`、`GITHUB_TOKEN`，然后配置中通过`$`进行获取和使用
* 整体的配置对应如下：

```yaml
before_deploy:
- npm run tsdoc # 生成文档
- git config --local user.name "Genluo"
- git config --local user.email "isgenluo@gmail.com"

after_deploy:
- npm install github-release-from-changelog -g
- github-release-from-changelog

deploy:
  - provider: npm # 包发布部署
    email: 1461304646@qq.com
    api_key:
      secure: [token]
    on:
      branch: master
      tags: true
    skip_cleanup: true
  - provider: pages # API文档部署
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    keep_history: true
    on:
      branch: master
      tags: true

```

# 其他

## 1. 告警配置

```yaml
notifications:
  email:
    recipients:
      - isgenluo@gamil.com
    on_success: never
    on_failure: always
```

详细配置点击: [click me](https://docs.travis-ci.com/user/notifications/)

## 2. 值得借鉴

整个CI流程配置针对新手不是很友好，收集了一些友好的方式，可以借鉴

* [release-it](https://github.com/release-it/release-it#changelog): release需要的能力及其于一身，同时还提供非常灵活的插件机制

### 1) `api_key`配置错误

建议直接通过官方`travis cli`进行设置，安装方法[click me](https://docs.travis-ci.com/user/deepsource/#install-cli-and-push-artifacts)，后续对照文档执行相关命令
